#!/bin/sh
# Zaza setup check.
#
# Verifies the toolchain, reports which optional examples your machine can run,
# and runs the Zig test suite. Safe to run repeatedly.
#
#   ./setup.sh
#
# Exits non-zero if Zig is missing or the test suite fails. Missing optional
# tools are warnings, not failures.

set -eu

ROOT_DIR=$(cd "$(dirname "$0")" && pwd)
cd "$ROOT_DIR"

SUPPORTED_ZIG="0.14.1 0.15.2"

if [ -t 1 ]; then
    C_RESET=$(printf '\033[0m')
    C_BOLD=$(printf '\033[1m')
    C_GREEN=$(printf '\033[0;32m')
    C_YELLOW=$(printf '\033[0;33m')
    C_RED=$(printf '\033[0;31m')
else
    C_RESET='' C_BOLD='' C_GREEN='' C_YELLOW='' C_RED=''
fi

ok()   { printf '%s  ok %s %s\n'   "$C_GREEN" "$C_RESET" "$1"; }
warn() { printf '%swarn %s %s\n'   "$C_YELLOW" "$C_RESET" "$1"; }
fail() { printf '%sfail %s %s\n'   "$C_RED" "$C_RESET" "$1"; }
head1() { printf '\n%s%s%s\n' "$C_BOLD" "$1" "$C_RESET"; }

UNAVAILABLE=""
note_unavailable() {
    UNAVAILABLE="${UNAVAILABLE}  $1
"
}

# ---------------------------------------------------------------------------
# Required: Zig
# ---------------------------------------------------------------------------

head1 "Toolchain"

if ! command -v zig >/dev/null 2>&1; then
    fail "zig is not on PATH"
    printf '\n'
    printf 'Install Zig 0.14.1 or 0.15.2 from https://ziglang.org/download/\n'
    printf 'and make sure the binary is on PATH, then run ./setup.sh again.\n'
    exit 1
fi

ZIG_BIN=$(command -v zig)
ZIG_VERSION=$(zig version)
ok "zig $ZIG_VERSION ($ZIG_BIN)"

ZIG_SUPPORTED=0
for v in $SUPPORTED_ZIG; do
    if [ "$ZIG_VERSION" = "$v" ]; then
        ZIG_SUPPORTED=1
    fi
done

if [ "$ZIG_SUPPORTED" -eq 0 ]; then
    warn "zig $ZIG_VERSION is untested. Zaza is verified on $SUPPORTED_ZIG."
    warn "The build may fail on std library changes between releases."
fi

# ---------------------------------------------------------------------------
# The ./zig wrapper
#
# Nested build steps (package-consumer, cross-compile-cli, rust-interop, and
# example-matrix) invoke ./zig by name. The wrapper is machine-local and
# gitignored, so a fresh clone does not have one.
# ---------------------------------------------------------------------------

head1 "Wrapper"

if [ -x "$ROOT_DIR/zig" ]; then
    ok "./zig wrapper present"
else
    cat > "$ROOT_DIR/zig" <<EOF
#!/bin/sh
# Generated by setup.sh. Machine-local; not tracked by git.
set -eu
ROOT_DIR="\$(cd "\$(dirname "\$0")" && pwd)"
ZIG_BIN="\${ZIG_REAL:-$ZIG_BIN}"
: "\${ZIG_GLOBAL_CACHE_DIR:=\$ROOT_DIR/.zig-cache-global}"
: "\${ZIG_LOCAL_CACHE_DIR:=\$ROOT_DIR/.zig-cache}"
export ZIG_GLOBAL_CACHE_DIR ZIG_LOCAL_CACHE_DIR
exec "\$ZIG_BIN" "\$@"
EOF
    chmod +x "$ROOT_DIR/zig"
    ok "./zig wrapper created (points at $ZIG_BIN)"
fi

# ---------------------------------------------------------------------------
# Optional tools
# ---------------------------------------------------------------------------

head1 "Optional tools"

check_optional() {
    tool=$1
    examples=$2
    version_cmd=$3

    if command -v "$tool" >/dev/null 2>&1; then
        version=$(eval "$version_cmd" 2>/dev/null | head -n 1)
        ok "$tool ${version:+- $version}"
    else
        warn "$tool not found"
        note_unavailable "$examples (needs $tool)"
    fi
}

check_optional git \
    "cmake_shim, cmake_combo, cmake_net, juce, zaza-juce" \
    "git --version"

check_optional cmake \
    "cmake_shim, cmake_combo, cmake_net, juce, zaza-juce" \
    "cmake --version"

check_optional cargo \
    "rust_interop" \
    "cargo --version"

check_optional node \
    "wasm_wasi, wasm_exports" \
    "node --version"

check_optional file \
    "cross_compile_cli report target" \
    "echo present"

# C++20 modules need a clang++ that supports them. zig c++ does not.
MODULES_CXX=${ZAZA_MODULES_CXX:-/opt/homebrew/opt/llvm/bin/clang++}
if [ -x "$MODULES_CXX" ]; then
    ok "clang++ with modules - $MODULES_CXX"
else
    warn "no clang++ with C++20 module support at $MODULES_CXX"
    note_unavailable "cxx20_modules (set ZAZA_MODULES_CXX to a clang++ that supports C++20 modules)"
fi

if [ -n "$UNAVAILABLE" ]; then
    head1 "Unavailable without the tools above"
    printf '%s' "$UNAVAILABLE"
    printf '\nEverything else runs with Zig alone.\n'
else
    head1 "Examples"
    ok "every example is available on this machine"
fi

# ---------------------------------------------------------------------------
# Test suite
# ---------------------------------------------------------------------------

head1 "Tests"

printf 'ZAZA_EXAMPLES=none zig build test --summary all\n\n'

# ZAZA_EXAMPLES=none keeps the C++ examples out of the graph. Zig resolves every
# declared dependency while the graph is built, so leaving them on would fetch
# JUCE, curl, mbedtls, zlib, spdlog and fmt just to run the Zig tests.
if ZAZA_EXAMPLES=none zig build test --summary all; then
    head1 "Done"
    ok "setup complete"
    printf '\nNext:\n'
    printf '  ZAZA_EXAMPLES=hello-zaza zig build run-hello-zaza   # smallest example\n'
    printf '  zig build --list-steps                              # every target\n'
    printf '  zig build example-matrix                            # the whole verified surface\n'
    printf '\nDocs: docs/WIKI.md   Examples: examples/README.md\n'
else
    status=$?
    head1 "Done"
    fail "test suite failed"
    printf '\nSee the troubleshooting section of docs/WIKI.md.\n'
    exit "$status"
fi
